#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./batch.sh [macro] [threads]
#
# Examples:
#   ./batch.sh
#   ./batch.sh macros/run.mac 10
#   ./batch.sh ../validation_angle_distribution/validation_angle_162_primary_off.mac 10
#
# The script can be launched either from the project root or from build/.
# It always writes and merges ROOT output under the project-local data/ directory.

MACRO_ARG="${1:-macros/run.mac}"
THREADS="${2:-4}"
CALL_DIR="$(pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

find_project_root() {
  if command -v git >/dev/null 2>&1; then
    if git -C "${SCRIPT_DIR}" rev-parse --show-toplevel >/dev/null 2>&1; then
      git -C "${SCRIPT_DIR}" rev-parse --show-toplevel
      return 0
    fi
  fi

  if [[ -f "${SCRIPT_DIR}/CMakeLists.txt" && -f "${SCRIPT_DIR}/HB.cc" ]]; then
    echo "${SCRIPT_DIR}"
    return 0
  fi

  if [[ -f "${SCRIPT_DIR}/../CMakeLists.txt" && -f "${SCRIPT_DIR}/../HB.cc" ]]; then
    cd "${SCRIPT_DIR}/.." && pwd
    return 0
  fi

  if [[ -f "${SCRIPT_DIR}/CMakeCache.txt" ]]; then
    local cmake_home
    cmake_home="$(awk -F= '/^CMAKE_HOME_DIRECTORY:/{print $2; exit}' "${SCRIPT_DIR}/CMakeCache.txt")"
    if [[ -n "${cmake_home}" && -f "${cmake_home}/CMakeLists.txt" && -f "${cmake_home}/HB.cc" ]]; then
      cd "${cmake_home}" && pwd
      return 0
    fi
  fi

  echo "ERROR: cannot locate project root from ${SCRIPT_DIR}." >&2
  return 1
}

resolve_macro_path() {
  local macro="$1"

  if [[ "${macro}" = /* && -f "${macro}" ]]; then
    cd "$(dirname "${macro}")" && printf '%s/%s\n' "$(pwd)" "$(basename "${macro}")"
    return 0
  fi

  local candidates=(
    "${CALL_DIR}/${macro}"
    "${PROJECT_ROOT}/${macro}"
    "${SCRIPT_DIR}/${macro}"
  )

  for candidate in "${candidates[@]}"; do
    if [[ -f "${candidate}" ]]; then
      cd "$(dirname "${candidate}")" && printf '%s/%s\n' "$(pwd)" "$(basename "${candidate}")"
      return 0
    fi
  done

  echo "ERROR: macro file not found: ${macro}" >&2
  echo "Tried:" >&2
  printf '  %s\n' "${candidates[@]}" >&2
  return 1
}

if ! [[ "${THREADS}" =~ ^[0-9]+$ ]] || [[ "${THREADS}" -lt 1 ]]; then
  echo "ERROR: threads must be a positive integer."
  echo "Usage: $0 [macro] [threads]"
  exit 2
fi

PROJECT_ROOT="$(find_project_root)"
DATA_DIR="${PROJECT_ROOT}/data"
mkdir -p "${DATA_DIR}"

if [[ -x "${SCRIPT_DIR}/HB" ]]; then
  HB_EXE="${SCRIPT_DIR}/HB"
elif [[ -x "${PROJECT_ROOT}/HB" ]]; then
  HB_EXE="${PROJECT_ROOT}/HB"
elif [[ -x "${PROJECT_ROOT}/build/HB" ]]; then
  HB_EXE="${PROJECT_ROOT}/build/HB"
else
  echo "ERROR: HB executable not found."
  echo "Expected one of:"
  echo "  ${SCRIPT_DIR}/HB"
  echo "  ${PROJECT_ROOT}/HB"
  echo "  ${PROJECT_ROOT}/build/HB"
  exit 1
fi

MACRO_PATH="$(resolve_macro_path "${MACRO_ARG}")"

export HB_PROJECT_ROOT="${PROJECT_ROOT}"
export HB_DATA_DIR="${DATA_DIR}"

TAG="$(date +%Y%m%d_%H%M%S)"
TMP_DIR="${DATA_DIR}/.batch_tmp_${TAG}_$$"
BEFORE_LIST="${TMP_DIR}/before.txt"
AFTER_LIST="${TMP_DIR}/after.txt"
NEW_LIST="${TMP_DIR}/new.txt"
mkdir -p "${TMP_DIR}"

cleanup() {
  rm -rf "${TMP_DIR}"
}
trap cleanup EXIT

snapshot_root_files() {
  find "${DATA_DIR}" -maxdepth 1 -type f -name "*.root" -print | sort -u
}

snapshot_root_files > "${BEFORE_LIST}"

echo "============================================================"
echo "HB batch run"
echo "============================================================"
echo "Call dir   : ${CALL_DIR}"
echo "Script dir : ${SCRIPT_DIR}"
echo "Project    : ${PROJECT_ROOT}"
echo "Executable : ${HB_EXE}"
echo "Macro      : ${MACRO_PATH}"
echo "Threads    : ${THREADS}"
echo "Run tag    : ${TAG}"
echo "Data dir   : ${DATA_DIR}"
echo "Seed       : auto-generated by HB"
echo "============================================================"

set +e
cd "${PROJECT_ROOT}"
"${HB_EXE}" "${MACRO_PATH}" "${THREADS}"
HB_STATUS=$?
set -e

if [[ "${HB_STATUS}" -ne 0 ]]; then
  echo "ERROR: HB exited with status ${HB_STATUS}."
  echo "No merge attempted."
  exit "${HB_STATUS}"
fi

snapshot_root_files > "${AFTER_LIST}"
comm -13 "${BEFORE_LIST}" "${AFTER_LIST}" > "${NEW_LIST}"
mapfile -t NEW_ROOT_FILES < "${NEW_LIST}"

if [[ "${#NEW_ROOT_FILES[@]}" -eq 0 ]]; then
  echo "WARNING: no new ROOT files detected in ${DATA_DIR}."
  exit 0
fi

echo "============================================================"
echo "New ROOT files from this run"
echo "============================================================"
printf '  %s\n' "${NEW_ROOT_FILES[@]}"

if ! command -v hadd >/dev/null 2>&1; then
  echo "ERROR: hadd was not found in PATH."
  echo "ROOT may not be configured in this shell."
  echo "Generated ROOT files were not merged."
  exit 1
fi

merge_class() {
  local class_name="$1"
  local pattern="^${class_name}_.*_t[0-9]+\.root$"
  local files=()

  for f in "${NEW_ROOT_FILES[@]}"; do
    local base
    base="$(basename "${f}")"
    if [[ "${base}" =~ ${pattern} ]]; then
      files+=("${f}")
    fi
  done

  if [[ "${#files[@]}" -eq 0 ]]; then
    echo "No ${class_name} thread ROOT files generated; skipping ${class_name} hadd."
    return 0
  fi

  if [[ "${#files[@]}" -eq 1 ]]; then
    echo "Only one ${class_name} thread ROOT file generated; no ${class_name} hadd needed:"
    echo "  ${files[0]}"
    return 0
  fi

  local out_file="${DATA_DIR}/${class_name}_merged_${TAG}.root"
  echo "============================================================"
  echo "Merging ${class_name} ROOT files"
  echo "============================================================"
  echo "Output: ${out_file}"
  hadd -f "${out_file}" "${files[@]}"

  if [[ "${CLEAN_THREADS:-1}" == "1" ]]; then
    echo "CLEAN_THREADS=1, deleting ${class_name} thread files:"
    printf '  %s\n' "${files[@]}"
    rm -f "${files[@]}"
  fi
}

merge_class reaction
merge_class event
merge_class track
merge_class step

# ---------------------------------------------------------------------
# Append a provenance record to data.log (next to HB.cc): which merged
# ROOT file(s) this run produced, and the effective (non-comment) macro
# commands used.
# ---------------------------------------------------------------------
LOG_FILE="${PROJECT_ROOT}/data.log"
{
  echo "======================================================================"
  echo "run tag : ${TAG}   date : $(date '+%Y-%m-%d %H:%M:%S')   threads : ${THREADS}"
  echo "--- merged output files ---"
  merged_found=0
  for cls in reaction event track step; do
    mf="${DATA_DIR}/${cls}_merged_${TAG}.root"
    if [[ -f "${mf}" ]]; then
      echo "  ${mf}"
      merged_found=1
    fi
  done
  if [[ "${merged_found}" -eq 0 ]]; then
    printf '  %s\n' "${NEW_ROOT_FILES[@]}"
  fi
  echo "--- effective macro commands ---"
  if [[ -f "${MACRO_PATH}" ]]; then
    grep -vE '^[[:space:]]*(#|$)' "${MACRO_PATH}" | sed 's/^/    /'
  fi
  echo ""
} >> "${LOG_FILE}"
echo "Provenance appended to ${LOG_FILE}"

echo "============================================================"
echo "Batch run complete"
echo "============================================================"
echo "Merged files are in ${DATA_DIR} with tag ${TAG}."
