/run/initialize

/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# Beam
/gun/particle proton
/gun/energy 165 keV

# Output control: reaction-only validation
/output/saveReaction true
/output/saveEvent false
/output/saveTrack false
/output/saveStep false
/output/printConfig

# Use only the 165-keV and 675-keV resonance models.
# Background should be zero in this mode.
/h11b/evaluatedCrossSection model
/h11b/backgroundMode phaseSpace

# Validation-only bias. Not for production physics.
/h11b/crossSectionBiasFactor 1000000000
/h11b/backgroundBiasFactor 1
/h11b/gammaBiasFactor 1000000000

/h11b/enable165GammaCapture true
/h11b/enable675GammaCapture false

/h11b/enable165PrimaryAngularDistribution false
/h11b/165PrimaryAngularA1 0.0
/h11b/165PrimaryAngularA2 0.0

/h11b/enable165Alpha1SecondaryAngularCorrelation true
/h11b/165Alpha1SecondaryA2 -0.489
/h11b/165Alpha1SecondaryA4 0.647

# 165 gamma angular distribution under test
/h11b/enable165Gamma0AngularDistribution false
/h11b/165Gamma0AngularA1 0.8
/h11b/165Gamma0AngularA2 0.5

/h11b/enable675PrimaryAngularDistribution false
/h11b/675PrimaryAngularA1 0.0
/h11b/675PrimaryAngularA2 0.0

/h11b/enable675Alpha1SecondaryAngularCorrelation true
/h11b/675Alpha1SecondaryA2 -1.064
/h11b/675Alpha1SecondaryA4 0.180

/h11b/enable675GammaAngularDistribution false
/h11b/675GammaAngularA1 0.0
/h11b/675GammaAngularA2 0.0

/h11b/printConfig

/run/beamOn 200000
