/run/initialize

/output/saveReaction true
/output/saveEvent true
/output/saveTrack true
/output/saveStep true
/output/printConfig

/h11b/crossSectionBiasFactor 1000000
/h11b/gammaBiasFactor 1
/h11b/enableDirectDecay false
/h11b/165SequentialDecayFraction 1.0
/h11b/675SequentialDecayFraction 1.0
/h11b/165BWScaleFactor 1.0
/h11b/675ScaleFactor 0.0
/h11b/enable165GammaCapture false
/h11b/enable675GammaCapture false
/h11b/printConfig

/gun/particle proton
/gun/energy 165 keV
/run/beamOn 1000
