/run/initialize

/output/saveReaction true
/output/saveEvent true
/output/saveTrack false
/output/saveStep false
/output/printConfig

/h11b/crossSectionBiasFactor 1000000
/h11b/gammaBiasFactor 10000
/h11b/enableDirectDecay true
/h11b/165SequentialDecayFraction 0.99
/h11b/675SequentialDecayFraction 0.99
/h11b/165BWScaleFactor 1.0
/h11b/675ScaleFactor 1.0
/h11b/enable165GammaCapture true
/h11b/enable675GammaCapture true
/h11b/printConfig

/gun/particle proton
/gun/energy 675 keV
/run/beamOn 100000
