#!/usr/bin/env bash
set -euo pipefail

events=100000
jobs=4

while [[ $# -gt 0 ]]; do
  case "$1" in
    --events)
      events="$2"
      shift 2
      ;;
    --jobs)
      jobs="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: bash validation/kinematics/run_kinematics_validation.sh [--events N] [--jobs J]"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
hb="$repo_root/build/HB"
macro_dir="$script_dir/macros"
output_dir="$script_dir/output"
plot_dir="$script_dir/plots"
report_dir="$script_dir/reports"
summary="$report_dir/kinematics_validation_summary.md"

if [[ ! -x "$hb" ]]; then
  echo "Missing executable: $hb" >&2
  echo "Build the project first, for example: cmake --build build" >&2
  exit 1
fi

mkdir -p "$output_dir" "$plot_dir" "$report_dir"

macros=(
  "validation_kinematics_165alpha.mac"
  "validation_kinematics_675alpha.mac"
  "validation_kinematics_direct.mac"
  "validation_kinematics_165gamma.mac"
  "validation_kinematics_675gamma.mac"
)

declare -A root_for_macro
overall_status=0

latest_reaction_root() {
  find "$repo_root/data" -maxdepth 1 -type f \( -name 'reaction_merged_*.root' -o -name 'reaction_*_t*.root' \) -printf '%T@ %p\n' 2>/dev/null \
    | sort -n \
    | tail -n 1 \
    | cut -d' ' -f2-
}

write_temp_macro() {
  local src="$1"
  local dst="$2"
  awk -v events="$events" '
    /^\/run\/beamOn[[:space:]]+/ {
      print "/run/beamOn " events
      next
    }
    { print }
  ' "$src" > "$dst"
}

run_validator() {
  local title="$1"
  local report_file="$2"
  shift 2

  {
    echo
    echo "## $title"
    echo
    echo '```text'
  } >> "$summary"

  if "$@" > "$report_file" 2>&1; then
    cat "$report_file" >> "$summary"
  else
    local rc=$?
    overall_status=1
    cat "$report_file" >> "$summary"
    {
      echo
      echo "validator exit code: $rc"
    } >> "$summary"
  fi

  {
    echo '```'
  } >> "$summary"
}

cat > "$summary" <<EOF
# Reaction Kinematics Validation Summary

Generated by \`validation/kinematics/run_kinematics_validation.sh\`.

Requested events per macro: \`$events\`
Requested jobs: \`$jobs\`

## Input ROOT Files

EOF

for macro in "${macros[@]}"; do
  macro_path="$macro_dir/$macro"
  if [[ ! -f "$macro_path" ]]; then
    echo "Missing macro: $macro_path" >&2
    exit 1
  fi

  before="$(latest_reaction_root || true)"
  tmp_macro="$(mktemp "/tmp/${macro%.mac}.XXXXXX.mac")"
  write_temp_macro "$macro_path" "$tmp_macro"

  echo "Running $macro with /run/beamOn $events on $jobs worker thread(s)"
  (cd "$repo_root" && bash ./batch.sh "$jobs" "$tmp_macro")

  after="$(latest_reaction_root || true)"
  if [[ -z "$after" || "$after" == "$before" ]]; then
    echo "Could not identify a new reaction_merged_*.root file for $macro" >&2
    exit 1
  fi

  root_for_macro["$macro"]="$after"
  link_name="$output_dir/${macro%.mac}_$(basename "$after")"
  ln -sfn "$after" "$link_name"
  echo "- \`$macro\`: \`$after\` (linked as \`$link_name\`)" >> "$summary"
done

{
  echo
  echo "## Branch Availability"
} >> "$summary"

for macro in "${macros[@]}"; do
  root_file="${root_for_macro[$macro]}"
  report_file="$report_dir/${macro%.mac}_branches.txt"
  run_validator "Branch availability: $macro" "$report_file" \
    python3 "$script_dir/scripts/inspect_reaction_branches.py" "$root_file"
done

{
  echo
  echo "## Four-Momentum Closure"
} >> "$summary"

for macro in validation_kinematics_165alpha.mac validation_kinematics_675alpha.mac validation_kinematics_direct.mac; do
  root_file="${root_for_macro[$macro]}"
  channel="all"
  [[ "$macro" == "validation_kinematics_165alpha.mac" ]] && channel="0"
  [[ "$macro" == "validation_kinematics_675alpha.mac" ]] && channel="1"
  [[ "$macro" == "validation_kinematics_direct.mac" ]] && channel="2"
  run_validator "Four-momentum closure: $macro" "$report_dir/${macro%.mac}_four_momentum.txt" \
    python3 "$script_dir/scripts/validate_four_momentum_closure.py" \
      --root "$root_file" --channel "$channel" --outdir "$plot_dir" \
      --report "$report_dir/${macro%.mac}_four_momentum_report.txt"
done

{
  echo
  echo "## Q-Value And Energy Budget"
} >> "$summary"

for macro in validation_kinematics_165alpha.mac validation_kinematics_675alpha.mac validation_kinematics_direct.mac; do
  root_file="${root_for_macro[$macro]}"
  channel="all"
  [[ "$macro" == "validation_kinematics_165alpha.mac" ]] && channel="0"
  [[ "$macro" == "validation_kinematics_675alpha.mac" ]] && channel="1"
  [[ "$macro" == "validation_kinematics_direct.mac" ]] && channel="2"
  run_validator "Q-value budget: $macro" "$report_dir/${macro%.mac}_qvalue.txt" \
    python3 "$script_dir/scripts/validate_qvalue_energy_budget.py" \
      --root "$root_file" --channel "$channel" \
      --report "$report_dir/${macro%.mac}_qvalue_report.txt"
done

{
  echo
  echo "## Sequential Decay Checks"
} >> "$summary"

run_validator "Sequential checks: validation_kinematics_165alpha.mac" "$report_dir/validation_kinematics_165alpha_sequential.txt" \
  python3 "$script_dir/scripts/validate_sequential_decay_kinematics.py" \
    --root "${root_for_macro[validation_kinematics_165alpha.mac]}" --channel 0 \
    --report "$report_dir/validation_kinematics_165alpha_sequential_report.txt"

run_validator "Sequential checks: validation_kinematics_675alpha.mac" "$report_dir/validation_kinematics_675alpha_sequential.txt" \
  python3 "$script_dir/scripts/validate_sequential_decay_kinematics.py" \
    --root "${root_for_macro[validation_kinematics_675alpha.mac]}" --channel 1 \
    --report "$report_dir/validation_kinematics_675alpha_sequential_report.txt"

{
  echo
  echo "## Direct 3-Alpha Phase-Space Checks"
} >> "$summary"

run_validator "Direct phase space: validation_kinematics_direct.mac" "$report_dir/validation_kinematics_direct_phase_space.txt" \
  python3 "$script_dir/scripts/validate_direct_3alpha_phase_space.py" \
    --root "${root_for_macro[validation_kinematics_direct.mac]}" --channel 2 --outdir "$plot_dir" \
    --report "$report_dir/validation_kinematics_direct_phase_space_report.txt"

{
  echo
  echo "## Gamma Capture Checks"
} >> "$summary"

run_validator "Gamma capture: validation_kinematics_165gamma.mac" "$report_dir/validation_kinematics_165gamma_gamma.txt" \
  python3 "$script_dir/scripts/validate_gamma_capture_kinematics.py" \
    --root "${root_for_macro[validation_kinematics_165gamma.mac]}" --channel 3 \
    --report "$report_dir/validation_kinematics_165gamma_gamma_report.txt"

run_validator "Gamma capture: validation_kinematics_675gamma.mac" "$report_dir/validation_kinematics_675gamma_gamma.txt" \
  python3 "$script_dir/scripts/validate_gamma_capture_kinematics.py" \
    --root "${root_for_macro[validation_kinematics_675gamma.mac]}" --channel 3 \
    --report "$report_dir/validation_kinematics_675gamma_gamma_report.txt"

{
  echo
  echo "## Plots"
  echo
  find "$plot_dir" -maxdepth 1 -type f -name '*.png' -printf '- `%p`\n' | sort
  echo
  echo "## PASS/WARN/FAIL Summary"
  echo
  grep -h '^\[[A-Z]*\]' "$report_dir"/*.txt "$report_dir"/*_report.txt 2>/dev/null | sort || true
} >> "$summary"

echo "Wrote $summary"
exit "$overall_status"
