/run/initialize

/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/gun/particle proton
/gun/energy 675 keV

/output/saveReaction true
/output/saveEvent false
/output/saveTrack false
/output/saveStep false
/output/printConfig

/h11b/crossSectionBiasFactor 1000000

/h11b/enableDirectDecay false
/h11b/165SequentialDecayFraction 0.99
/h11b/675SequentialDecayFraction 0.99
/h11b/165BWScaleFactor 1.0
/h11b/675ScaleFactor 1.0

/h11b/enable165GammaCapture false
/h11b/enable675GammaCapture false
/h11b/gammaBiasFactor 1

/h11b/enable165PrimaryAngularDistribution false
/h11b/165PrimaryAngularA1 0.0
/h11b/165PrimaryAngularA2 0.0
/h11b/enable165Alpha1SecondaryAngularCorrelation true
/h11b/165Alpha1SecondaryA2 -0.489
/h11b/165Alpha1SecondaryA4 0.647
/h11b/enable165Gamma0AngularDistribution true
/h11b/165Gamma0AngularA1 -0.17757009345794392
/h11b/165Gamma0AngularA2 0.13084112149532712

/h11b/enable675PrimaryAngularDistribution false
/h11b/675PrimaryAngularA1 0.0
/h11b/675PrimaryAngularA2 0.0
/h11b/enable675Alpha1SecondaryAngularCorrelation true
/h11b/675Alpha1SecondaryA2 -1.064
/h11b/675Alpha1SecondaryA4 0.180
/h11b/675AlphaDecayModel legacyLegendreA2A4

/h11b/enable675GammaAngularDistribution false
/h11b/675GammaAngularA1 0.0
/h11b/675GammaAngularA2 0.0

/h11b/printConfig
/run/beamOn 20000
