/run/initialize

/control/verbose 2

# Explicit beam setting for validation.
/gun/particle proton
/gun/energy 165 keV

# Output control for generator-level validation.
/output/saveReaction true
/output/saveEvent false
/output/saveTrack false
/output/saveStep false
/output/printConfig

# Validation-only cross-section bias.
/h11b/crossSectionBiasFactor 1000000

/h11b/enableDirectDecay true
/h11b/165SequentialDecayFraction 0.0
/h11b/675SequentialDecayFraction 0.0

# 165-keV primary alpha angular distribution
/h11b/enable165PrimaryAngularDistribution false
/h11b/165PrimaryAngularA1 0.0
/h11b/165PrimaryAngularA2 0.0

# 165-keV alpha1 secondary alpha angular correlation
/h11b/enable165Alpha1SecondaryAngularCorrelation true
/h11b/165Alpha1SecondaryA2 -0.489
/h11b/165Alpha1SecondaryA4 0.647

# 165-keV gamma0 angular distribution
/h11b/enable165Gamma0AngularDistribution true
/h11b/165Gamma0AngularA1 -0.17757009345794392
/h11b/165Gamma0AngularA2 0.13084112149532712

# 675-keV primary alpha angular distribution
/h11b/enable675PrimaryAngularDistribution false
/h11b/675PrimaryAngularA1 0.0
/h11b/675PrimaryAngularA2 0.0

# 675-keV alpha1 secondary alpha angular correlation
/h11b/enable675Alpha1SecondaryAngularCorrelation true
/h11b/675Alpha1SecondaryA2 -1.064
/h11b/675Alpha1SecondaryA4 0.180

# 675-keV gamma angular distribution
/h11b/enable675GammaAngularDistribution false
/h11b/675GammaAngularA1 0.0
/h11b/675GammaAngularA2 0.0

# Only 165-keV gamma capture is enabled.
/h11b/enable165GammaCapture true
/h11b/enable675GammaCapture false

/h11b/gammaBiasFactor 10000
/h11b/printConfig
/run/beamOn 200000
